parameters:
- name: terraformVersion
  type: string
- name: workingDirectory
  type: string
- name: stage
  type: string
  default: lint


steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: "Terraform install version ${{ parameters.terraformVersion }}"
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - task: Bash@3
    displayName: "Terraform format"
    inputs:
      targetType: "inline"
      script: terraform fmt -check -recursive -diff ${{ parameters.workingDirectory }}

  - task: TerraformTaskV2@0
    displayName: "Terraform init ${{ parameters.stage }}"
    inputs:
      provider: "azurerm"
      command: "init"
      workingDirectory: ${{ parameters.workingDirectory }}/tf
      commandOptions: "-reconfigure"
